Changes to if statement for GHA (#376)

diff --git a/.github/workflows/integration.yml b/.github/workflows/integration.yml
--- a/.github/workflows/integration.yml
+++ b/.github/workflows/integration.yml
@@ -9,7 +9,7 @@ name: Integration tests
 jobs:
   integration-trusted:
     runs-on: ubuntu-latest
-    if: (startsWith(github.event.client_payload.pull_request.head.sha, github.event.client_payload.slash_command.args.named.sha) && github.event_name == 'repository_dispatch') || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository)
+    if: (contains(github.event.client_payload.pull_request.head.sha, github.event.client_payload.slash_command.args.named.sha) && github.event_name == 'repository_dispatch') || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository)
     strategy:
       matrix:
         target:
@@ -26,7 +26,7 @@ jobs:
         run: |
           SHAINPUT=$(echo ${{github.event.client_payload.slash_command.args.named.sha}} | cut -c1-7)
           echo ${#SHAINPUT}
-          if [ ${#SHAINPUT} -le 7 ]; then echo "error::input sha not at least 7 characters long" ; exit 1
+          if [ ${#SHAINPUT} -le 6 ]; then echo "error::input sha not at least 7 characters long" ; exit 1
           else echo "done"
           fi
 
