Condense jobs for GHA and verify sha input from ok-to-test (#367)
* Condense jobs for GHA and verify sha input from ok-to-test

* syntax

* syntax

* fix yaml

* syntax

diff --git a/.github/workflows/integration.yml b/.github/workflows/integration.yml
--- a/.github/workflows/integration.yml
+++ b/.github/workflows/integration.yml
@@ -9,6 +9,7 @@ name: Integration tests
 jobs:
   integration-trusted:
     runs-on: ubuntu-latest
+    if: (startsWith(github.event.client_payload.pull_request.head.sha, github.event.client_payload.slash_command.args.named.sha) && github.event_name == 'repository_dispatch') || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository)
     strategy:
       matrix:
         target:
@@ -20,56 +21,34 @@ jobs:
           echo ${{ github.event_name }}
           echo ${{ github.event.client_payload }}
 
-      - id: sha-input
+      - id: verify-sha-input
         if: github.event_name == 'repository_dispatch'
         run: |
           SHAINPUT=$(echo ${{github.event.client_payload.slash_command.args.named.sha}} | cut -c1-7)
-          echo $SHAINPUT
+          echo $SHAINPUT | wc -c
+          if [ $SHAINPUT -ge 7 ]; then echo "error::input sha not at least 7 characters long" ; exit 1
+          else echo "done"
+          fi
 
-      - id: sha-head
+      - name: pull_request actions/checkout
+        uses: actions/checkout@v2
+        if: github.event_name == 'pull_request'
+
+      - name: repository_dispatch actions/checkout
+        uses: actions/checkout@v2
         if: github.event_name == 'repository_dispatch'
-        run: |
-          SHAHEAD=$(echo ${{github.event.client_payload.pull_request.head.sha}} | cut -c1-7)
-          echo $SHAHEAD
-
-      - uses: actions/checkout@v2
-        if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository
-
-      - uses: actions/setup-go@v2
-        if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository
-        with:
-          go-version: '1.15.5'
-
-      - name: Install dependencies
-        if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository
-        run: make setup
-
-      - name: make ${{ matrix.target }} integration trusted
-        if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository
-        env:
-          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.REVIEWDOG_GITHUB_API_TOKEN }}
-          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
-          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
-          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
-          SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
-        run: make ${{ matrix.target }}
-
-      - uses: actions/checkout@v2
-        if: github.event_name == 'repository_dispatch' && steps.sha-input.outputs.SHAINPUT == steps.sha-head.outputs.SHAHEAD
         with:
           ref: 'refs/pull/${{ github.event.client_payload.pull_request.number }}/merge'
 
-      - uses: actions/setup-go@v2
-        if: github.event_name == 'repository_dispatch' && steps.sha-input.outputs.SHAINPUT == steps.sha-head.outputs.SHAHEAD
+      - name: setup-go
+        uses: actions/setup-go@v2
         with:
           go-version: '1.15.5'
 
       - name: Install dependencies
-        if: github.event_name == 'repository_dispatch' && steps.sha-input.outputs.SHAINPUT == steps.sha-head.outputs.SHAHEAD
         run: make setup
 
-      - name: make ${{ matrix.target }} integration fork
-        if: github.event_name == 'repository_dispatch' && steps.sha-input.outputs.SHAINPUT == steps.sha-head.outputs.SHAHEAD
+      - name: make ${{ matrix.target }} integration
         env:
           REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.REVIEWDOG_GITHUB_API_TOKEN }}
           SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
@@ -78,8 +57,9 @@ jobs:
           SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
         run: make ${{ matrix.target }}
 
-      - uses: actions/github-script@v3
-        if: github.event_name == 'repository_dispatch' && steps.sha-input.outputs.SHAINPUT == steps.sha-head.outputs.SHAHEAD
+      - name: set fork job status
+        uses: actions/github-script@v3
+        if: github.event_name == 'repository_dispatch'
         id: update-check-run
         env:
           number: ${{ github.event.client_payload.pull_request.number }}
@@ -101,6 +81,7 @@ jobs:
             });
 
             const check = checks.check_runs.filter(c => c.name === process.env.job);
+            console.log(check);
 
             const { data: result } = await github.checks.update({
               ...context.repo,
